bsideproject/KoLiving_FE

.eslintrc.json
components/Button/Button.module.scss
components/Button/Button.tsx
pages/index.tsx

fix : eslintrc.json endline sequence 수정  
feat : pages, Button Component 추가

2023.06.05

---

components/Button/Button.tsx
components/Link/HyperLink.module.scss
components/Link/HyperLink.tsx
pages/index.tsx
public/locales/en/common.json

[feat] index.js Button, Link Component 적용
[style] Button Component css 적용
[style] Link Component css 적용

[feat] Link Component 추가

---

components/Radio/Radio.module.scss
components/Radio/Radio.tsx
pages/index.tsx

[feat] Radio Component 추가
- Radio.test
- Radio.Module.scss
- index.tsx 수정

[feat] Radio Component 추가

---

components/Typography/Typography.module.scss
components/Typography/Typography.tsx
pages/index.tsx

[feat] Typography 추가
- Typography component 추가
- Typography module scss 추가

[feat] Typography 추가

---

components/Textarea/Textarea.module.scss
components/Textarea/Textarea.tsx
pages/index.tsx

[feat] Textarea Component 추가
- textarea.tsx 추가
- textarea.moduel.scss 추가
- index.tsx radio, textarea component 주석

[feat] Textarea Component 추가

---

components/Textarea/Textarea.tsx

[feat] Textarea.tsx 
eslint 규칙 맞게 수정

[feat] Textarea.tsx eslint 규칙 맞게 수정

---

components/Button/Button.tsx
components/Image/CustomImage.module.scss
components/Image/CustomImage.tsx

[feat] CustomImage Component 추가
[feat] Button Component 생성 방법 변경

[feat] CustomImage Component 추가

---

components/Button/Button.module.scss
components/Button/Button.tsx
tailwind.config.js

[feat] Button Component tailwindcss 수정
- Button size, color 속성 추가

[feat] Button Component tailwindcss 수정

---

pages/404.tsx
pages/index.tsx
stories/Button.stories.tsx

[feat] Button.stories.tsx 사용하지 않는 코드 수정
- 404.tsx ( 오류 처리 페이지 ), 수정 필요함
- Button.Stories.tsx 미사용 import 구문 수정

[feat] Button.stories.tsx 사용하지 않는 코드 수정

---

components/Typography/Typography.module.scss
components/Typography/Typography.tsx

[feat] Typography css 수정
- figma 보고 수정했는데, 다른 방법 생각해봐야 할듯...

[feat] Typography css 수정

---

pages/index.tsx

index.tsx 
하단 사용하지 않는 Component 주석 제거

[feat] index.ts (필요없는 주석 제거)

---

pages/_error.tsx

[feat] _error.tsx

---

container/Login/login.tsx
public/locales/en/common.json
public/locales/ko/common.json

[feat] Login Component 2차개발
- Email, Password 유효성 검사 추가~

[feat] Login Component 2차개발

---

container/Login/login.tsx

[feat] login.tsx eslint 수정

---

components/Image/CustomImage.tsx

[feat] CustomImage.tsx

---

pages/resetPassword.tsx

[feat] Reset Password Page 수정

---

components/Modal/ModalBox.tsx
components/Modal/ModalContainer.tsx
pages/resetPassword.tsx

[feat] ResetPassword Page 기능 추가

[feat] ResetPassword Page 기능 추가

---

pages/login.tsx
pages/resetPassword.tsx

[bug] ResetPassword 페이지 버그 수정

---

pages/resetPassword.tsx

[bug] build 실패해서 다시 올려봅니다람쥐..

---

components/Chip/Chip.tsx

[chore] build 오류 수정

---

components/Chip/Chip.tsx

[bug] Chip Component 빌드 오류 실패 수정

[bug] Chip Component 빌드 오류 실패 수정

---

components/Chip/Chip.tsx

[feat] Chip Component 1차 개발

---

components/Toggle/Toggle.tsx
public/icons/off.svg
public/icons/on.svg

[feat] Toggle Component 1차 개발!

[feat] Toggle Component 1차 개발

---

components/Toggle/Toggle.tsx

[feat] Toggle Component Transition-x px 조정

[feat] Toggle Component Transition-x px 조정

---

components/Toggle/Toggle.tsx

[feat] Toggle Component 사용하지 않는 svg import 부분 제거

[feat] Toggle Component 사용하지 않는 svg import 부분 제거

---

components/index.tsx
pages/resetPassword/step1.tsx

[feat] components index.tsx 추가 및 export 로직 수정

[feat] components index.tsx 추가 및 export 로직 수정

---

pages/roomList.tsx

[feat] RoomList 수정

---

pages/filter.tsx
pages/roomList.tsx
public/icons/filter.svg

[feat] Filter 관련 소스 우선 Commit

---

components/Select/Select.module.scss
components/Select/Select.tsx
components/Toggle/Toggle.tsx
pages/filter/filter.tsx

Select Component disabled 기능 추가!

[feat] Filter Component 우선 Commit!

---

components/Button/Button.module.scss
components/Button/Button.tsx
pages/filter/filter.tsx

[feat] Filter Page 추가, Button Component 다시보기!!

[feat] Filter Page 추가, Button Component 다시보기

---

components/Button/Button.module.scss
pages/filter/filter.tsx

[feat] Filter Page 변경 (Button 크기 조정)

[feat] Filter Page 변경

---

components/Input/Input.tsx

[feat] Input Component Disabled 속성 추가

[feat] Input Component Disabled 속성 추가

---

components/Input/Input.tsx

[bug] Input Component 중복된 disabled 속성 제거

[bug] Input Component 중복된 disabled 속성 제거

---

components/Toggle/Toggle.tsx
pages/room/filter.tsx
pages/room/roomList.tsx

[bug] Toggle 움직일 때마다, focus 이동하는 부분 수정

[bug] Toggle 움직일 때마다, focus 이동하는 부분 수정

---

pages/room/filter.tsx
public/js/guDongList.ts

[fix] Filter 부분 버그 수정 ㅠㅠ

---

pages/index.tsx
pages/room/filter.tsx

[feat] Main Page RoomList Filter 추가

[feat] Main Page RoomList Filter 추가

---

pages/index.tsx

[fix] index.tsx, getLayout 오류 수정

[fix] index.tsx, getLayout 오류 수정

---

.env
.env.production

[feat] env 파일 ip 정보 수정

---

pages/room/filter.tsx

[fix] 오류 우선 제거...!! 내일까지 마무리하자!

[fix] 오류 우선 제거...!! 내일까지 마무리하자!

---

pages/index.tsx
pages/room/filter.tsx

[feat] RoomList, Filter 우선 커밋...!!

[feat] RoomList, Filter 우선 커밋...!!

---

components/Typography/Typography.tsx
pages/index.tsx
pages/room/filter.tsx

[feat] Filter Component 우선 커밋!!

[feat] Filter Component 우선 커밋

---

components/Chip/Chip.tsx
components/Select/Select.tsx
pages/room/filter.tsx

[fix] Filter Component figma 보고 부분 수정

[fix] Filter Component figma 보고 부분 수정

---

pages/index.tsx
pages/room/filter.tsx
public/locales/en/common.json
public/locales/en/filter.json
public/locales/ko/filter.json

[fix] Filter Component 크기 조절

---

components/Modal/ModalBox.tsx
components/Modal/ModalContainer.tsx
components/layouts/RoomListLayout.tsx
pages/index.tsx
pages/room/addRoom.tsx

[feat] addRooms Modal, Filter에서 복사해서 우선 Commit.!!

[feat] addRooms Modal, Filter에서 복사해서 우선 Commit.!!

---

pages/room/addRoom/step1.tsx

[feat] 오우... 우선 커밋

---

components/Typography/Typography.module.scss
pages/room/addRoom/step1.tsx

[feat] Room Post Step1 우선 추가

---

components/Modal/ModalBox.tsx
pages/signup/step1.tsx

- step2 로 바로 넘어가는 것이 아닌 얼럿창이 뜨는 거였음 # 작업
- 모달 버튼에 buttonName 넘기도록 수정

[feat] 모달 형태 변경 및 가입 플로우 수정

---

pages/index.tsx

[feat] RoomList Main 우선 커밋

---

components/Nav/Nav.module.scss
components/Nav/Nav.tsx

[feat] RoomList 디테일 1차 수정 레츠고

---

components/Card/Card.tsx
components/RoomCard/RoomCard.tsx

[feat] Room List Like 버튼 및 Mouse Pointer 수정

[feat] Room List Like 버튼 및 Mouse Pointer 수정

---

components/RoomCard/RoomCard.tsx

[feat] Room 디자인 2차 수정!!

---

components/Filter/Filter.tsx
pages/index.tsx

[feat] RoomList Main 수정

---

pages/index.tsx
public/types/filter.ts

[feat] RoomList 수정 중 우선 커밋...!

[feat] RoomList 수정 중 우선 커밋...!

---

pages/index.tsx
public/locales/en/common.json
public/locales/en/roomList.json
public/locales/ko/common.json
public/locales/ko/roomList.json

[feat] Filter 삭제 안되던 문제 우선 1차 개발

[feat] Filter 삭제 안되던 문제 우선 1차 개발

---

pages/index.tsx

[feat] RoomList 필터 부분 1차 수정

---

pages/index.tsx

[feat] index.tsx 수정

---

components/Input/Input.module.scss
components/Input/Input.tsx
pages/room/addRoom/step1.tsx

[feat] input Tag disabled 시 bg컬러 수정

[feat] input Tag disabled 시 bg컬러 수정

---

components/Calendar/Calendar.module.scss
components/Calendar/Calendar.tsx
pages/room/addRoom/step1.tsx

[feat] 룸등록 Step1 1차 수정

---

pages/room/addRoom/step1.tsx
pages/room/addRoom/step2.tsx

[feat] 룸 등록 step2, step3 이동기능만 추가

[feat] 룸 등록 step2, step3 이동기능만 추가

---

pages/room/addRoom/step2.tsx

[feat] useRouter 파라미터 정보 추가

---

pages/room/addRoom/step1.tsx

[refactor] step1 Button 관련 로직 수정

[refactor] step1 Button 관련 로직 수정

---

components/Select/Select.tsx

[fix] Select Component  NextJS 버그 수정

[fix] Select Component  NextJS 버그 수정

---

components/Stepper2/Stepper2.module.scss
components/Stepper2/Stepper2.tsx
components/index.tsx
pages/room/addRoom/step2.tsx

[feat] Step2 수정, Stepper Component 추가!

[feat] Step2 수정, Stepper Component 추가!

---

components/Stepper2/Stepper2.tsx

[feat] Stepper2 Component 자리수 늘어나면 위치 바뀌는 이슈 수정

[feat] Stepper2 Component 자리수 늘어나면 위치 바뀌는 이슈 수정

---

components/Stepper2/Stepper2.tsx

[feat] Stepper2 라인 수정

---

pages/room/addRoom/step2.tsx

[feat] 룸 등록- Step2 상세 내용 수정

---

components/Textarea/Textarea.tsx
pages/room/addRoom/step3.tsx
public/icons/rectangle.svg
public/icons/rectanglePlus.svg

[feat] TextArea Component 수정,Step3 수정

[feat] TextArea Component 수정,Step3 수정

---

components/File/FileUpload.tsx
components/index.tsx
package.json
pages/room/addRoom/step3.tsx
yarn.lock

[feat] react-images-uploading 라이브러리 추가 및 step3 수정

[feat] react-images-uploading 추가 및 step3 수정

---

components/File/FileUpload.tsx

[feat] FileUpload -> Close 기능 추가

[feat] FileUpload -> Close 기능 추가

---

components/File/FileUpload.tsx

[feat] Room 등록 step3 이미지 등록 부분 수정

[feat] Room 등록 step3 이미지 등록 부분 수정

---

components/File/FileUpload.tsx
components/layouts/RoomListLayout.tsx
pages/index.tsx
pages/room/addRoom/step1.tsx
pages/room/addRoom/step2.tsx
pages/room/addRoom/step3.tsx

[feat] Room 등록 부분 수정 (router -> Modal)

[feat] Room 등록 부분 수정 (router -> Modal)

---

components/Stepper2/Stepper2.tsx

[feat] Stepper Component 수정

---

components/Nav/Nav.tsx
components/RoomCard/RoomCard.tsx
pages/profile/index.tsx

[feat] UserProfile 우선 커밋!!

---

components/Modal/ModalBox.tsx
components/ProfileCard/index.tsx

[feat] User Profile 수정

---

components/File/FileUpload.module.scss
components/File/FileUpload.tsx
components/ProfileCard/index.tsx
pages/profile/editProfile.tsx
pages/room/addRoom/step3.tsx

[feat] EditProfile Image Upload 부분 수정

[feat] EditProfile Image Upload 부분 수정

---

pages/profile/editProfile.tsx

[fix] editProfile name build 오류 수정

[fix] editProfile name build 오류 수정

---

pages/userInfo/myPostings.tsx

[feat] 포스팅된 룸 정보 없을 때 페이지 상세 내용 수정

[feat] 포스팅된 룸 정보 없을 때 페이지 상세 내용 수정

---

pages/room/addRoom/step1.tsx
pages/room/addRoom/step2.tsx
pages/room/addRoom/step3.tsx
pages/userInfo/myPostings.tsx

[fix] 룸등록 step3 페이지이동 오류 수정

---

components/Nav/Nav.tsx

[feat] Nav 영역, 페이지 이동 경로 수정

---

pages/index.tsx

[feat] RoomList Page 수정

---

pages/userInfo/editProfile.tsx

[feat] editProfile 부분 수정

---

components/Nav/Nav.tsx
components/RoomCard/RoomCard.tsx
pages/liked/index.tsx
pages/room/addRoom/step2.tsx

[feat] Liked 페이지 껍데기 배포

---

components/File/FileUpload.tsx
components/ProfileCard/index.tsx
pages/userInfo/editProfile.tsx
pages/userInfo/myPostings.tsx

[fix] editProfile 이미지 가운데 위치하도록 수정

[fix] editProfile 이미지 가운데 위치하도록 수정

---

components/Modal/Modal.module.scss
components/Modal/ModalBox.tsx
components/Modal/ModalContainer.tsx
components/ProfileCard/index.tsx

[feat] UserProfile 탭에서 Logout 버튼 클릭 시 팝업 추가

[feat] UserProfile 탭에서 Logout 버튼 클릭 시 팝업 추가

---

components/Header/Header.tsx
pages/room/[id].tsx
public/icons/recycleBin.svg

[feat] Room 상세 삭제 버튼 추가

---

pages/liked/index.tsx

[feat] Liked page 수정

---

pages/liked/index.tsx

[feat] Liked Page Title 부분 수정

---

components/ProfileCard/index.tsx

[feat] myPage -> logout 부분 수정

---

components/RoomCard/RoomCard.tsx

[feat] roomList 메인 줄 깨짐 수정

---

components/RoomCard/RoomCard.tsx

[fix] RooCard Photos null 일 경우 예외처리 추가

[fix] RooCard Photos null 일 경우 예외처리 추가

---

pages/index.tsx

[feat] index.tsx Page 해야할일
까먹지말라능!!

[feat] index.tsx Page 해야할일

---

api/userInfo.ts
components/Nav/Nav.tsx
components/ProfileCard/index.tsx
context/UserInfoProvider.tsx
hooks/useUserInfo.ts
pages/_app.tsx
pages/index.tsx
pages/login.tsx
pages/userInfo/index.tsx

[feat] my Profile Api 연동!!! 이렇게 하는게 아닌가봄...... ㅠㅠㅠㅠㅠ

[feat] my Profile Api 연동!!!

---

api/userInfo.ts
components/Input/Input.tsx
components/ProfileCard/index.tsx
components/RoomCard/RoomCard.tsx
pages/liked/index.tsx
pages/userInfo/editProfile.tsx
pages/userInfo/index.tsx

[feat] MyProfile -> Edit Profile 2차 수정!!!

[feat] MyProfile -> Edit Profile 2차 수정

---

api/userInfo.ts
components/Nav/Nav.tsx
pages/userInfo/editProfile.tsx
public/types/user.ts

[feat] 프로필 정보 수정 1차 개발..

---

pages/userInfo/editProfile.tsx

[feat] 마이 프로필 오류 수정

---

pages/404.tsx
pages/room/addRoom/step1.tsx
pages/room/addRoom/step3.tsx
pages/userInfo/editProfile.tsx
pages/userInfo/index.tsx

[fix] eslint 오류 수정!!

---

pages/index.tsx
pages/userInfo/index.tsx

[feat] UserProfile Page 수정

---

pages/index.tsx

[fix] userInfo 메인 페이지 오류 수정

---

components/Input/Input.tsx
pages/userInfo/editProfile.tsx

[feat] Email Reaonly 처리

---

api/userInfo.ts
pages/userInfo/editProfile.tsx

[feat] EditProfile 부분 수정... ><

[feat] EditProfile 부분 수정... ><

---

components/RoomCard/RoomCard.tsx
pages/userInfo/editProfile.tsx

[feat] EditProfile 부분 우선 수정!

---

api/signup.ts
pages/resetPassword/step1.tsx

[feat] resetPassword API 추가

---

pages/resetPassword/step1.tsx

[feat] 비밀번호 재설정 우선 커밋!!

---

pages/userInfo/editProfile.tsx

[feat] EditProfile 코드 수정

---

pages/userInfo/editProfile.tsx

[feat] Profile 에서 이미지 업로드 안되는 부분 수정!!!

[feat] Profile 에서 이미지 업로드 안되는 부분 수정!

---

pages/userInfo/editProfile.tsx

[feat] editProfile 수정 이미지 업로드 하는 부분...제발...!

[feat] editProfile 수정 이미지 업로드 하는 부분...제발...!

---

pages/userInfo/editProfile.tsx

[feat] 제발.....!!

---

pages/userInfo/editProfile.tsx

[fix] 프로필 수정 -> 이미지 업로드 수정

---

pages/userInfo/editProfile.tsx

[feat] 프로필 이미지 업로드 최종 수정

---

pages/userInfo/editProfile.tsx

[feat] 프로필 수정 Complete 버튼 비활성/활성 로직 추가

[feat] 프로필 수정 Complete 버튼 비활성/활성 로직 추가
